apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kimyoungwoo613/back:2.0
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_IP
          value: mongodb.default.svc.cluster.local
        - name: MONGO_PORT
          value: "27017"
        volumeMounts:
        - mountPath: /etc/localtime
          name: backend-claim0
      volumes:
      - name: backend-claim0
        persistentVolumeClaim:
          claimName: backend-claim0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  labels:
    app: backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/backend-storage/b1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: backend
  name: backend-claim0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

